import { defineConfig } from "tsdown";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		protocol: "src/protocol.ts",
		schema: "src/schema.ts",
		errors: "src/errors.ts",
		types: "src/types.ts",
		"peers/index": "src/peers/index.ts",
		"peers/default": "src/peers/default.ts",
		"peers/durable": "src/peers/durable.ts",
		"adapters/index": "src/adapters/index.ts",
		"adapters/types": "src/adapters/types.ts",
		"adapters/client": "src/adapters/client.ts",
		"adapters/server": "src/adapters/server.ts",
		"adapters/cloudflare-do": "src/adapters/cloudflare-do.ts",
		"codecs/index": "src/codecs/index.ts",
		"codecs/factory": "src/codecs/factory.ts",
		"codecs/json": "src/codecs/json.ts",
		"codecs/msgpack": "src/codecs/msgpack.ts",
		"codecs/cbor": "src/codecs/cbor.ts",
		"storage/index": "src/storage/index.ts",
		"storage/interface": "src/storage/interface.ts",
		"storage/sql": "src/storage/sql.ts",
		"storage/memory": "src/storage/memory.ts",
		"utils/index": "src/utils/index.ts",
		"utils/reconnect": "src/utils/reconnect.ts",
	},
	format: ["esm"],
	outDir: "dist",
	clean: true,
	dts: true,
	platform: "neutral",
});
